# Generated by Django 6.0.2 on 2026-02-08 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtworkGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('auction_house', 'Auction House'), ('dealership', 'Dealership'), ('museum', 'Museum'), ('gallery', 'Gallery'), ('other', 'Other')], max_length=50)),
                ('location', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('death_date', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('biography', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citation', models.CharField(help_text="e.g. 'Sotheby's Catalog, 1923'", max_length=500)),
                ('details', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('medium', models.CharField(blank=True, max_length=255)),
                ('dimensions', models.CharField(blank=True, max_length=100)),
                ('creation_date_text', models.CharField(blank=True, help_text="e.g. 'c. 1750'", max_length=100)),
                ('year_start', models.IntegerField(blank=True, null=True)),
                ('year_end', models.IntegerField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='artworks', to='provenance.artworkgroup')),
            ],
        ),
        migrations.CreateModel(
            name='ArtworkRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('possible_match', 'Possible Match (Is this the same?)'), ('copy_of', 'Copy Of'), ('pendant_to', 'Pendant To'), ('study_for', 'Study For')], default='possible_match', max_length=50)),
                ('certainty', models.CharField(choices=[('possible', 'Possible'), ('probable', 'Probable'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='possible', max_length=20)),
                ('reasoning', models.TextField(blank=True)),
                ('source_artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to='provenance.artwork')),
                ('target_artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to='provenance.artwork')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='ProvenanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.IntegerField(help_text='Order of events. Higher number = later.')),
                ('event_type', models.CharField(choices=[('creation', 'Creation'), ('acquisition', 'Acquisition'), ('sale', 'Sale'), ('transfer', 'Transfer'), ('lost', 'Lost'), ('found', 'Found'), ('loan', 'Loan')], default='acquisition', max_length=50)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('role', models.CharField(blank=True, help_text='e.g. Owner, Seller, Agent', max_length=100)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('display_date', models.CharField(blank=True, help_text="e.g. 'Early 20th Century'", max_length=100)),
                ('certainty', models.CharField(choices=[('proven', 'Proven'), ('likely', 'Likely'), ('possible', 'Possible'), ('unproven', 'Unproven'), ('false', 'False / Disproven')], default='proven', max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provenance', to='provenance.artwork')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='provenance.source')),
            ],
            options={
                'ordering': ['sequence_number'],
            },
        ),
    ]
