# Generated by Django 6.0.2 on 2026-02-08 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provenance', '0002_medium_artwork_medium_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='medium',
        ),
    ]
