# Generated by Django 6.0.2 on 2026-02-08 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provenance', '0003_remove_artwork_medium'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='medium_new',
            new_name='medium',
        ),
    ]
