# Generated by Django 6.0.2 on 2026-02-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provenance', '0004_rename_medium_new_artwork_medium'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='notes',
            field=models.TextField(blank=True, help_text='General notes or content remarks.'),
        ),
        migrations.AddField(
            model_name='source',
            name='notes',
            field=models.TextField(blank=True, help_text='Remarks about the archival document.'),
        ),
        migrations.AlterField(
            model_name='source',
            name='details',
            field=models.TextField(blank=True, help_text='Specific pages, digital locations, etc.'),
        ),
    ]
