# Generated by Django 6.0.2 on 2026-02-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provenance', '0005_artwork_notes_source_notes_alter_source_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provenanceevent',
            name='event_type',
            field=models.CharField(choices=[('creation', 'Creation'), ('acquisition', 'Acquisition'), ('sale', 'Sale'), ('transfer', 'Transfer'), ('mentioned', 'Mentioned'), ('lost', 'Lost'), ('found', 'Found'), ('loan', 'Loan')], default='acquisition', max_length=50),
        ),
    ]
