# Generated by Django 6.0.2 on 2026-02-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provenance', '0006_alter_provenanceevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='type',
            field=models.CharField(choices=[('archive', 'Archive Document (Archivalie)'), ('literature', 'Literature (Literatur)'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
