# Generated by Django 6.0.2 on 2026-02-08 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provenance', '0007_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provenanceevent',
            name='event_type',
            field=models.CharField(choices=[('creation', 'Creation'), ('acquisition', 'Acquisition'), ('sale', 'Sale'), ('transfer', 'Transfer'), ('mentioned', 'Mentioned'), ('lost', 'Lost'), ('found', 'Found'), ('loan', 'Loan'), ('exhibition', 'Exhibited')], default='acquisition', max_length=50),
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
                ('auction_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='provenance.organization')),
                ('source', models.ForeignKey(blank=True, help_text='Link to the auction catalog.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='provenance.source')),
            ],
        ),
        migrations.AddField(
            model_name='provenanceevent',
            name='auction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='provenance.auction'),
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibitions', to='provenance.organization')),
                ('source', models.ForeignKey(blank=True, help_text='Link to the exhibition catalog.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='provenance.source')),
            ],
        ),
        migrations.AddField(
            model_name='provenanceevent',
            name='exhibition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='provenance.exhibition'),
        ),
    ]
