# Generated by Django 5.0.2 on 2026-02-14 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provenance', '0010_alter_artwork_id_alter_artworkgroup_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('place', models.CharField(blank=True, max_length=255)),
                ('start_date', models.CharField(blank=True, max_length=100, null=True)),
                ('end_date', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='provenanceevent',
            name='auction',
        ),
        migrations.RemoveField(
            model_name='exhibition',
            name='location',
        ),
        migrations.RemoveField(
            model_name='exhibition',
            name='source',
        ),
        migrations.RemoveField(
            model_name='provenanceevent',
            name='exhibition',
        ),
        migrations.RenameField(
            model_name='artwork',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='family_name',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='creation_date_text',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='dimensions',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='year_end',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='year_start',
        ),
        migrations.RemoveField(
            model_name='artworkrelationship',
            name='certainty',
        ),
        migrations.RemoveField(
            model_name='person',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='provenanceevent',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='provenanceevent',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='provenanceevent',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='provenanceevent',
            name='date_start',
        ),
        migrations.RemoveField(
            model_name='provenanceevent',
            name='display_date',
        ),
        migrations.RemoveField(
            model_name='provenanceevent',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='provenanceevent',
            name='price',
        ),
        migrations.RemoveField(
            model_name='provenanceevent',
            name='role',
        ),
        migrations.RemoveField(
            model_name='provenanceevent',
            name='source',
        ),
        migrations.RemoveField(
            model_name='source',
            name='citation',
        ),
        migrations.RemoveField(
            model_name='source',
            name='details',
        ),
        migrations.RemoveField(
            model_name='source',
            name='notes',
        ),
        migrations.AddField(
            model_name='artwork',
            name='dimension',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='person',
            name='first_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='provenanceevent',
            name='date',
            field=models.CharField(blank=True, help_text='Date as input type text', max_length=100),
        ),
        migrations.AddField(
            model_name='provenanceevent',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provenance_events', to='provenance.person'),
        ),
        migrations.AddField(
            model_name='provenanceevent',
            name='sources',
            field=models.ManyToManyField(blank=True, related_name='provenance_events', to='provenance.source'),
        ),
        migrations.AddField(
            model_name='source',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='source',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artwork',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artworkgroup',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='artworkrelationship',
            name='type',
            field=models.CharField(choices=[('possible_match', 'Possible Match'), ('copy_of', 'Copy Of'), ('pendant_to', 'Pendant To'), ('study_for', 'Study For')], default='possible_match', max_length=50),
        ),
        migrations.AlterField(
            model_name='medium',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='death_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='provenanceevent',
            name='artwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provenance_events', to='provenance.artwork'),
        ),
        migrations.AlterField(
            model_name='provenanceevent',
            name='certainty',
            field=models.CharField(blank=True, choices=[('proven', 'Proven'), ('likely', 'Likely'), ('possible', 'Possible'), ('unproven', 'Unproven'), ('false', 'False / Disproven')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='provenanceevent',
            name='event_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='provenanceevent',
            name='sequence_number',
            field=models.IntegerField(help_text='Order of events.'),
        ),
        migrations.AlterField(
            model_name='source',
            name='type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='medium',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mediums', to='provenance.arttype'),
        ),
        migrations.AddField(
            model_name='provenanceevent',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provenance_events', to='provenance.institution'),
        ),
        migrations.AddField(
            model_name='institution',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institutions', to='provenance.institutiontype'),
        ),
        migrations.DeleteModel(
            name='Auction',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='Exhibition',
        ),
    ]
