# Generated by Django 5.0.2 on 2026-02-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provenance', '0011_arttype_institution_institutiontype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
