# Generated by Django 5.0.2 on 2026-02-14 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provenance', '0012_institution_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auctions', to='provenance.institution')),
                ('sources', models.ManyToManyField(blank=True, related_name='auctions', to='provenance.source')),
            ],
        ),
        migrations.CreateModel(
            name='AuctionPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('expert', 'Expert'), ('auctioneer', 'Auctioneer')], max_length=20)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_persons', to='provenance.auction')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_auctions', to='provenance.person')),
            ],
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_start', models.CharField(blank=True, max_length=100)),
                ('date_end', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exhibitions', to='provenance.institution')),
                ('sources', models.ManyToManyField(blank=True, related_name='exhibitions', to='provenance.source')),
            ],
        ),
    ]
