# Generated by Django 5.0.2 on 2026-02-22 22:18

from django.db import migrations

def migrate_event_types(apps, schema_editor):
    ProvenanceEvent = apps.get_model('provenance', 'ProvenanceEvent')
    EventType = apps.get_model('provenance', 'EventType')

    for event in ProvenanceEvent.objects.all():
        if event.event_type:
            event_type_name = event.event_type.strip()
            if event_type_name:
                event_type_obj, created = EventType.objects.get_or_create(name=event_type_name)
                event.event_type_new = event_type_obj
                event.save()

def rollback_event_types(apps, schema_editor):
    ProvenanceEvent = apps.get_model('provenance', 'ProvenanceEvent')
    for event in ProvenanceEvent.objects.all():
        if event.event_type_new:
            event.event_type = event.event_type_new.name
            event.save()

class Migration(migrations.Migration):

    dependencies = [
        ('provenance', '0014_eventtype_provenanceevent_event_type_new'),
    ]

    operations = [
        migrations.RunPython(migrate_event_types, reverse_code=rollback_event_types),
    ]
