# Generated by Django 5.0.2 on 2026-02-22 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provenance', '0015_migrate_event_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provenanceevent',
            name='event_type',
        ),
        migrations.RenameField(
            model_name='provenanceevent',
            old_name='event_type_new',
            new_name='event_type',
        ),
    ]
