# Generated by Django 5.0.2 on 2026-02-22 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provenance', '0016_remove_provenanceevent_event_type_new_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provenanceevent',
            name='auction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provenance_events', to='provenance.auction'),
        ),
        migrations.AddField(
            model_name='provenanceevent',
            name='exhibition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provenance_events', to='provenance.exhibition'),
        ),
    ]
