# Generated by Django 5.0.2 on 2026-03-12 23:18

import django.db.models.deletion
from django.db import migrations, models


def migrate_sources_to_through_model(apps, schema_editor):
    ProvenanceEvent = apps.get_model('provenance', 'ProvenanceEvent')
    EventSource = apps.get_model('provenance', 'EventSource')
    
    # We use the through model's manager to create relationships
    for event in ProvenanceEvent.objects.all():
        # During this migration, event.sources might still refer to the old M2M table
        # or it might be in an inconsistent state if we use state-only operations.
        # A safer way is to use the raw database table if we know it.
        # But if we haven't 'Altered' the field yet in the DB, event.sources.all() should work.
        for source in event.sources.all():
            EventSource.objects.get_or_create(
                provenance_event=event,
                source=source
            )

class Migration(migrations.Migration):

    dependencies = [
        ('provenance', '0017_provenanceevent_auction_provenanceevent_exhibition'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_notes', models.CharField(blank=True, help_text='Additional notes for this source.', max_length=100)),
                ('provenance_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provenance.provenanceevent')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provenance.source')),
            ],
        ),
        # Move data to the new through model table before changing the field definition
        migrations.RunPython(migrate_sources_to_through_model),
        # Now change the field. To avoid the ValueError, we can use SeparateDatabaseAndState.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='provenanceevent',
                    name='sources',
                ),
                migrations.AddField(
                    model_name='provenanceevent',
                    name='sources',
                    field=models.ManyToManyField(blank=True, related_name='provenance_events', through='provenance.EventSource', to='provenance.source'),
                ),
            ],
            database_operations=[
                # In the database, the intermediate table for 'sources' still exists.
                # We don't need to do anything here if we want to keep the old data for a bit longer,
                # but eventually we should drop it. 
                # For now, let's just do nothing in the DB for the field swap, 
                # as AddField(through) doesn't create a new table in the DB if we don't want it to,
                # BUT wait, Django *will* expect the new table 'provenance_eventsource' to be used.
                # Since we already created it with CreateModel, we are good.
                
                # To be super safe and avoid errors, we can manually drop the old M2M table
                migrations.RunSQL(
                    "DROP TABLE IF EXISTS provenance_provenanceevent_sources;"
                ),
            ],
        ),
    ]
