# Generated by Django 5.0.2 on 2026-03-12 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provenance', '0018_add_eventsource_through'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artworks_direct', to='provenance.source'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='source_notes',
            field=models.CharField(blank=True, help_text='Additional notes for this source.', max_length=100),
        ),
    ]
