# Generated by Django 5.0.2 on 2026-03-13 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provenance', '0019_add_artwork_source_and_notes'),
    ]

def migrate_source_data(apps, schema_editor):
    ProvenanceEvent = apps.get_model('provenance', 'ProvenanceEvent')
    EventSource = apps.get_model('provenance', 'EventSource')
    for event in ProvenanceEvent.objects.all():
        # Get the first associated source from the EventSource through model
        first_event_source = EventSource.objects.filter(provenance_event=event).first()
        if first_event_source:
            event.source = first_event_source.source
            event.source_notes = first_event_source.source_notes
            event.save()

class Migration(migrations.Migration):

    dependencies = [
        ('provenance', '0019_add_artwork_source_and_notes'),
    ]

    operations = [
        # 1. Add new fields to ProvenanceEvent
        migrations.AddField(
            model_name='provenanceevent',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provenance_events', to='provenance.source'),
        ),
        migrations.AddField(
            model_name='provenanceevent',
            name='source_notes',
            field=models.CharField(blank=True, help_text='Additional notes for this source.', max_length=100),
        ),
        # 2. Migrate data
        migrations.RunPython(migrate_source_data),
        # 3. Remove old fields and model
        migrations.RemoveField(
            model_name='provenanceevent',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='source',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='source_notes',
        ),
        migrations.DeleteModel(
            name='EventSource',
        ),
    ]
