# Generated by Django 5.0.2 on 2026-03-13 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provenance', '0020_single_source_per_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provenanceevent',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provenance_events_legacy', to='provenance.source'),
        ),
        migrations.CreateModel(
            name='ProvenanceEventSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provenance.provenanceevent')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provenance.source')),
            ],
        ),
        migrations.AddField(
            model_name='provenanceevent',
            name='sources',
            field=models.ManyToManyField(related_name='provenance_events', through='provenance.ProvenanceEventSource', to='provenance.source'),
        ),
    ]
