# Generated by Django 5.0.2 on 2026-03-13 12:48

from django.db import migrations


def migrate_source_data(apps, schema_editor):
    ProvenanceEvent = apps.get_model('provenance', 'ProvenanceEvent')
    ProvenanceEventSource = apps.get_model('provenance', 'ProvenanceEventSource')
    
    for event in ProvenanceEvent.objects.all():
        if event.source:
            ProvenanceEventSource.objects.create(
                event=event,
                source=event.source,
                notes=event.source_notes or ""
            )

class Migration(migrations.Migration):

    dependencies = [
        ('provenance', '0021_alter_provenanceevent_source_provenanceeventsource_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_source_data, reverse_code=migrations.RunPython.noop),
    ]
