# Generated by Django 5.0.2 on 2026-03-13 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provenance', '0022_migrate_source_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provenanceevent',
            name='source',
        ),
        migrations.RemoveField(
            model_name='provenanceevent',
            name='source_notes',
        ),
    ]
