# Generated by Django 5.0.2 on 2026-03-13 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provenance', '0023_remove_provenanceevent_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provenanceeventsource',
            name='notes',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
