# Generated by Django 5.0.2 on 2026-08-15 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provenance', '0024_alter_provenanceeventsource_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('long term', 'Long Term'), ('singular', 'Singular')], max_length=20)),
                ('date', models.CharField(blank=True, max_length=100)),
                ('place', models.CharField(blank=True, max_length=255)),
                ('entity1_institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_entity1', to='provenance.institution')),
                ('entity1_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_entity1', to='provenance.person')),
                ('entity2_institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_entity2', to='provenance.institution')),
                ('entity2_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_entity2', to='provenance.person')),
            ],
        ),
    ]
