# Generated by Django 5.0.2 on 2026-08-15 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provenance', '0025_interaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='InteractionSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=150)),
                ('interaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provenance.interaction')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provenance.source')),
            ],
        ),
        migrations.AddField(
            model_name='interaction',
            name='sources',
            field=models.ManyToManyField(related_name='interactions', through='provenance.InteractionSource', to='provenance.source'),
        ),
    ]
