# Generated by Django 5.0.2 on 2026-08-19 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provenance', '0026_interaction_notes_interactionsource_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institution',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['family_name', 'first_name']},
        ),
    ]
