# Generated by Django 5.0.2 on 2026-08-19 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provenance', '0027_alter_institution_options_alter_person_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provenanceevent',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provenance_events', to='provenance.person'),
        ),
    ]
