# Generated by Django 5.0.2 on 2026-08-19 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provenance', '0028_alter_provenanceevent_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='medium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='artworks', to='provenance.medium'),
        ),
        migrations.AlterField(
            model_name='artworkrelationship',
            name='source_artwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relationships_from', to='provenance.artwork'),
        ),
        migrations.AlterField(
            model_name='artworkrelationship',
            name='target_artwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relationships_to', to='provenance.artwork'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auctions', to='provenance.institution'),
        ),
        migrations.AlterField(
            model_name='auctionperson',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person_auctions', to='provenance.person'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exhibitions', to='provenance.institution'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='institutions', to='provenance.institutiontype'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='entity1_institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interactions_as_entity1', to='provenance.institution'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='entity1_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interactions_as_entity1', to='provenance.person'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='entity2_institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interactions_as_entity2', to='provenance.institution'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='entity2_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interactions_as_entity2', to='provenance.person'),
        ),
        migrations.AlterField(
            model_name='interactionsource',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='provenance.source'),
        ),
        migrations.AlterField(
            model_name='medium',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mediums', to='provenance.arttype'),
        ),
        migrations.AlterField(
            model_name='provenanceevent',
            name='auction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provenance_events', to='provenance.auction'),
        ),
        migrations.AlterField(
            model_name='provenanceevent',
            name='event_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provenance_events', to='provenance.eventtype'),
        ),
        migrations.AlterField(
            model_name='provenanceevent',
            name='exhibition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provenance_events', to='provenance.exhibition'),
        ),
        migrations.AlterField(
            model_name='provenanceevent',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provenance_events', to='provenance.institution'),
        ),
        migrations.AlterField(
            model_name='provenanceeventsource',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='provenance.source'),
        ),
    ]
